### ISSUE TITLE
Preserve inodes?

### ISSUE THREAD

**Issue by oblitum** [adlerosn/cicpoffs#1]
I'm not sure whether this is possible, but, I'm missing that inodes are different for the same file, but accessed with different case. Is it possible to make them equal?

This program is very useful, so thanks for sharing it. It is just not perfect due to that because I have some programs where it doesn't work because those programs check for inodes to know whether the filesystem is case sensitive or not, and it ends up identifying cicpoffs mounts as case-sensitive due to that.

**Comment by oblitum** [comment]
Managed to fix my issue, just needed to pass `-o use_ino` :-)

**Comment by adlerosn** [comment]
Well observed!
 I've taken a quick look at program behavior on inodes and it seems to be a case-sensitive global counter.
 I'll take a longer look next weekend, so I can try figuring out a way to preserve inode stability.
 Thanks for reporting.

**Comment by adlerosn** [comment]
Thanks for the knowledge. It has been added to:
https://github.com/adlerosn/cicpoffs/commit/c23816fe12f0e252860ed6bc00816293d79c98db
